### ISSUE TITLE
Missing Scripts folder?

### ISSUE THREAD

**Issue by ADefWebserver** [canhorn/EventHorizon.Blazor.Dynamic.Scripting#1]
I build all projects and run the Server Project, then the Client project, then click the Run Script button:

![image](https://user-images.githubusercontent.com/1857799/90966138-be227780-e483-11ea-9f3e-dd46f047db05.png)

Then get:

![image](https://user-images.githubusercontent.com/1857799/90966148-df836380-e483-11ea-8e11-25d9c3bc6a2d.png)

And yes that directory is _not_ there?

![image](https://user-images.githubusercontent.com/1857799/90966161-0b9ee480-e484-11ea-9660-ec47c3baac65.png)

Thanks!

**Comment by canhorn** [comment]
Thanks for finding that, it should be fixed now. 
The .gitignore was a little too eager.

**Comment by ADefWebserver** [comment]
Yeah that fixed it 👍 
![image](https://user-images.githubusercontent.com/1857799/90989464-c5fb1e00-e54e-11ea-9782-d6b111dea84a.png)
