### ISSUE TITLE
Information Only: Running Using Visual Studio

### ISSUE THREAD

**Issue by ADefWebserver** [canhorn/EventHorizon.Blazor.Dynamic.Scripting#2]
If you are using Visual Studio, here is a way to get the project to run properly:

![image](https://user-images.githubusercontent.com/1857799/90989564-8bde4c00-e54f-11ea-8ac5-1f4fe9431ec9.png)

![image](https://user-images.githubusercontent.com/1857799/90989565-8ed93c80-e54f-11ea-879d-7515a9026b8d.png)

![image](https://user-images.githubusercontent.com/1857799/90989566-913b9680-e54f-11ea-85da-6ebbe072542f.png)

![image](https://user-images.githubusercontent.com/1857799/90989570-9a2c6800-e54f-11ea-91dd-7c945307c2d0.png)

**Comment by canhorn** [comment]
Added a Wiki page and update Readme with link.
